# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: GG4aCrossover
email: viethoangquoc1402@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Tất tần tật về IOS, kể cả những điều thú vị khác nữa.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: viet142
github_username:  gg4acrossover

# Build settings
markdown: kramdown
