name: GG4aCrossover
description: Blogging about IOS and life
meta_description: "IOS and something interesting in life"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'https://gg4acrossover.github.io'
google_analytics: ''
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'gg4acrossover.github.io'
author:         'VietHQ'
