# Page settings

baseurl = "http://gg4acrossover.github.io/"
languageCode = "en-us"
title = "Hoang Quoc Viet resume"
theme = "hugo-orbit-theme"
googleAnalytics = ""

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    description = "Hugo Responsive Resume/CV Theme for Developers"
    author = "Pavel Kanyshev"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Hoàng Quốc Việt"
        tagline = "IOS Developer"
        avatar = "profile.jpg"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: hoangquocviet1402@gmail.com"
        title = "hoangquocviet1402@gmail.com"

        [[params.contact.list]]
        class = "website"
        icon = "fa-globe"
        url = "//gg4acrossover.github.io/hugosite"
        title = "gg4acrossover.github.io/hugosite"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/viethoangquoc1402"
        title = "linkedin.com/in/viethoangquoc1402"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/gg4acrossover"
        title = "github.com/gg4acrossover"

        [[params.contact.list]]
        class = "twitter"
        icon = "fa-twitter"
        url = "//twitter.com/viet142"
        title = "@viet142"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "Kỹ sư CNTT"
        college = "Học viện kỹ thuật quân sự"
        dates = "2011 - 2013"

        [[params.education.list]]
        degree = "Cử nhân CNTT"
        college = "Viện đại học Mở"
        dates = "2006 - 2009"

    # Languages section
    [params.language]
        enable = true
        title = "Languages"

        [[params.language.list]]
        language = "Tiếng Việt"
        level = "Tiếng mẹ đẻ :D"

        [[params.language.list]]
        language = "English"
        level = "Giao tiếp cơ bản"

    # Interests section
    [params.interests]
        enable = true
        title = "Sở thích"

        [[params.interests.list]]
        interest = "Đọc sách"

        [[params.interests.list]]
        interest = "Bi.a"

        [[params.interests.list]]
        interest = "Bóng rổ"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = "Tôi có hơn 5 năm làm việc trong lĩnh vực lập trình mobile, cụ thể là IOS. Tôi đã đi qua nhiều môi trường, từ startup, outsource, product cho đến ...nhà nước nên dễ thích ứng với các môi trường làm việc khác nhau. Là người đam mê công nghệ, tôi có viết blog ghi chép lại những kiến thức mới, vừa để ghi nhớ cho bản thân, vừa chia sẻ với cộng đồng lập trình nói chung."

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "IOS Developer"
        dates = "2017 - Present"
        company = "VTVCab"
        details = "Làm các phần mềm liên quan đến play video. Tìm hiểu và tích hợp thư viện của đối tác vào hệ thống của trung tâm. Họp đưa ra giải pháp về công nghệ để áp dụng vào các ứng dụng mới của công ty. Review sản phẩm bên B."

        [[params.jobs.list]]
        position = "Mobile Leader"
        dates = "2016 - 2017"
        company = "Seta"
        details = "Làm product chuyên về thương mại điện tử. Sử dụng các công nghệ SignalR, KVO/KVC, custom layout vào trong project. Tạo base ứng dụng, review code của thành viên trong đội. Tìm hiểu requirement dự án và chia task. Đưa ra giải pháp công nghệ với các vấn đề gặp phải khi làm việc."

        [[params.jobs.list]]
        position = "IOS Deleloper, team leader"
        dates = "2014 - 2016"
        company = "VNext"
        details = "Lập trình game, ứng dụng outsource của công ty. Làm team leader 1 dự án về mạng xã hội ở bên Nhật. Tiếp xúc, làm quen với cách làm việc ở môi trường Nhật như horenso, kaizen."

        [[params.jobs.list]]
        position = "Cocos2dx developer"
        dates = "2012 - 2014"
        company = "StartUp"
        details = "Lập trình game sử dụng cocos2dx, viết bằng ngôn ngữ C++"

    # Projects section
    [params.projects]
        enable = true
        icon = "fa-archive"
        title = "Projects"
        intro = "Đã làm việc với các dự án thương mại điện tử, game, ứng dụng outsource như mạng xã hội, tin tức, học tiếng Nhật, ứng dụng bán quần áo, ..."

        [[params.projects.list]]
        title = "Network layer"
        url = "https://github.com/gg4acrossover/ONNetworkBehavior"
        tagline = "Opensource về phương pháp xây dựng network base"

        [[params.projects.list]]
        title = "GGBird"
        url = "https://github.com/gg4acrossover/GGBird"
        tagline = "Game mô phỏng flappy bird, viết trong 3 ngày khi học swift."

        [[params.projects.list]]
        title = "Progress"
        url = "https://github.com/gg4acrossover/ONProgressHUD"
        tagline = "Thư viện progress viết bằng swift"

        [[params.projects.list]]
        title = "Blog"
        url = "https://gg4acrossover.github.io/hugosite/"
        tagline = "Blog công nghệ, viết về những thứ xoay quanh lập trình mobile"

    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "ObjC/Swift"
        level = "98%"
                
        [[params.skills.list]]
        skill = "Javascript"
        level = "60%"

        [[params.skills.list]]
        skill = "C++"
        level = "80%"

        [[params.skills.list]]
        skill = "Photoshop"
        level = "60%"

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    # 
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
copyright = ""